{% set name = "sql-magic" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sql_magic-{{ version }}.tar.gz
  sha256: f54a08dda93b6b84f992ffc000d08ec491f44230a9f59e00aaf1b4d06c0f0324

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - findspark
    - ipython
    - jupyter
    - pandas
    - python >={{ python_min }}
    - sqlparse
    - traitlets

test:
  imports:
    - sql_magic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pivotal-legacy/sql_magic
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: 'Jupyter magic for writing SQL to interact with Spark/Hive and relational databases.'

extra:
  recipe-maintainers:
    - thewchan
